name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'  # Chạy mỗi ngày vào lúc 00:00 UTC
  push:
    branches:
      - main  # Bạn có thể thay 'main' bằng nhánh mà bạn muốn

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-git@v2

      - name: Add remote for upstream
        run: git remote add upstream https://github.com/levphuocthinh/CEO_MEMO.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Sync local repository with upstream
        run: git merge upstream/main --allow-unrelated-histories -m "Sync fork with upstream"
