name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'  # Chạy mỗi ngày vào lúc 00:00 UTC
  push:
    branches:
      - main  # Chạy khi có thay đổi push lên nhánh main

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add remote for upstream
        run: git remote add upstream https://github.com/levphuocthinh/CEO_MEMO.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Sync local repository with upstream
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Sync fork with upstream" || true

      - name: Resolve merge conflicts (except .gitignore)
        run: |
          # Giải quyết conflict cho README.md và các file khác
          git checkout --theirs README.md
          git add README.md
          
          # Bỏ qua conflict cho .gitignore
          git checkout --ours .gitignore
          git add .gitignore

      - name: Pull remote changes before pushing
        run: |
          git pull origin main --rebase  # Kéo các thay đổi mới nhất từ remote và rebase lên nhánh hiện tại

      - name: Commit merge changes
        run: git commit -m "Resolved merge conflicts and sync fork"

      - name: Push changes to fork
        run: git push origin main
